### ISSUE TITLE
Can I use tracer.ActiveSpan in JS?

### ISSUE THREAD

**Issue by rainmakerho** [opentracing/opentracing-javascript#121]
I can use tracer.ActiveSpan in C#. 
Can I use tracer.ActiveSpan in JS?

**Comment by osmanghoni1** [comment]
At this point in time it is not possible as it is not defined in [tracer.ts](https://github.com/opentracing/opentracing-javascript/blob/master/src/tracer.ts)

and will most likely require #112 to be completed first

**Comment by rainmakerho** [comment]
@osmanghoni1 , 
OK, Thank you.
