### ISSUE TITLE
automatic tracer

### ISSUE THREAD

**Issue by naseemkullah** [opentracing/opentracing-javascript#129]
Would it be possible to have an automatic tracer that traces express, redis, mysql and other common apps much like those offered by vendors? Without having to explicitly declare spans.

**Comment by naseemkullah** [comment]
Ideally we can build off https://github.com/RisingStack/opentracing-auto ... they seem to have the right idea, but repo seems a little under maintained.

**Comment by rochdev** [comment]
This will be implemented in [OpenTelemetry](https://opentelemetry.io/) which will supersede OpenTracing in the coming months. It will have an OpenTracing compatibility layer meaning you could benefit from auto instrumentation and other advanced features of OpenTelemetry without changing your existing OpenTracing code.
