### ISSUE TITLE
Inject and Extract with BINARY format

### ISSUE THREAD

**Issue by CHOMNANP** [opentracing/opentracing-javascript#130]
I have tried and cannot manage to get the Inject and extract with Binary work across 2 node on microservice. The communication between service is using rabitMQ.

Can anyone help guild me how to get it done?

**Comment by florianrusch** [comment]
Please correct me, if I'm wrong: For me it looks like there is no logic behind the `inject`/`extract` functions. 

https://github.com/opentracing/opentracing-javascript/blob/cb74683fefe5bd4d711eaa0c273f3fc17a6c3781/src/tracer.ts#L172-L179

**Comment by CHOMNANP** [comment]
I got a working way around with TEXT_MAP_FORMAT.
https://github.com/jaegertracing/jaeger-client-node/issues/370

Thank.
