### ISSUE TITLE
A naive backend implementation should be provided

### ISSUE THREAD

**Issue by bcronin** [opentracing/opentracing-javascript#3]
The repo should include a trivial backend implementation to make it obvious how to implement a compliant-OpenTracing JS tracing backend.

**Comment by AloisReitbauer** [comment]
Isn't this resolved with mock tracer?

**Comment by yurishkuro** [comment]
+1, mock tracer, or https://github.com/jaegertracing/jaeger-client-node, can be used as reference implementations.
