### ISSUE TITLE
release tags and debug-lib version

### ISSUE THREAD

**Issue by oibe** [opentracing/opentracing-javascript#51]
@bcronin 
Can you release a new version that contains tags, and debug-lib?

**Comment by bcronin** [comment]
Yes, sorry! I didn't realize I hadn't after the last set of changes.

(Also, let me know if there are others that need to be added to the `npm-owners` list)

**Comment by bcronin** [comment]
It's been pushed to NPM and tagged as `0.12.1`, to be clear.
