### ISSUE TITLE
TraceContext codec is not implemented correctly

### ISSUE THREAD

**Issue by bcronin** [opentracing/opentracing-javascript#6]
This code is intended to build packages for both Node.js and the browser.  It's unclear how to correctly implement the "binary encoding" without making assumptions about the platform (i.e. Buffer, Uint8Array, etc.). 

This does raise some concern that an implementation-detail may be creeping into the API.

**Comment by oibe** [comment]
Don't all versions of javascript support conversion to byte buffers?  If so then maybe we should add a method to the api such as "Uint8ArrayToByteArray".

**Comment by bcronin** [comment]
Thanks @oibe . I'm not sure what specific type you mean by "byte array" - but in any case, it does look like `Uint8Array` has fairly solid support across platforms: https://kangax.github.io/compat-table/es6/#test-typed_arrays_Uint8Array. That may be the best / most universal way to return binary data in the JS API.

**Comment by bcronin** [comment]
Issue is no longer relevant. The `inject` / `join` semantics have replaced this.
