### ISSUE TITLE
Creating a follows_from reference

### ISSUE THREAD

**Issue by ojkelly** [opentracing/opentracing-javascript#61]
I'm trying to write an implementation, but I'm not sure how to go about implementing follows_from.

It looks like this isn't implemented in `startSpan()` in `tracer.js`.

I've had a read through the git history and it looks like this may have been implemented at some point.

Can someone show how this should be done in an implementation, as well as an example of how to use it in practice.

I would expect it to work like this, based on how `childOf` works.

```javascript
const parentSpan = tracer.startSpan('parentOperation');
const childSpan = tracer.startSpan('childOperation', { followsFrom: parentSpan });
```

Thanks!

**Comment by yurishkuro** [comment]
The FOLLOWS_FROM reference can be added via `fields.references` array.

**Comment by ojkelly** [comment]
I tried:
```javascript
const childSpan: any = tracer.startSpan('followsFrom', {
  references: [
    {
      followsFrom: parentSpan,
    },
  ]
});
```

But then I realised it needs to be a `Reference` object, so I added the following to my `_startSpan` to allow the example in the OP to work.

```javascript
    if (fields.followsFrom) {
      // Convert from a Span or a SpanContext into a Reference.
      const followsFrom = opentracing.followsFrom(fields.followsFrom);
      if (fields.references) {
        fields.references.push(followsFrom);
      } else {
        fields.references = [followsFrom];
      }
      delete (fields.followsFrom);
    }
```

I'm still not sure if this is *how* it's meant to be implemented. For example as a user of my implementation, how would I create it?

**Comment by yurishkuro** [comment]
Are you asking as a user of the API or as the implementor of the tracer?  For the latter what you have above makes sense, but it's not part of the official API which only defines `fields.childOf`, not `fields.followsFrom`. As a user of the API, you would need to do
```
tracer.startSpan("operation name", {
    references: [opentracing.followsFrom(parentContext)]
})
```

**Comment by ojkelly** [comment]
I'm asking as both.

Thanks for the example and clarification, that helps quite a bit.

**Comment by yurishkuro** [comment]
https://github.com/opentracing/opentracing-javascript/pull/62

cc @ojkelly @bhs
