### ISSUE TITLE
What is the purpose of operationName in startSpan?

### ISSUE THREAD

**Issue by robsimmons** [opentracing/opentracing-javascript#63]
The API documentation suggests that the purpose is to allow a single-argument call to tracer.startSpan

```
tracer.startSpan({
    operationName: "makeRPC",
    tags: {...}
});
```

but the code doesn't actually support this single-argument setup.

**Comment by yurishkuro** [comment]
it's a leftover from previous API. Operation name is a required first argument.

**Comment by bhs** [comment]
@robsimmons thanks for bringing this up. Let me know if my PR clarifies things sufficiently.

**Comment by robsimmons** [comment]
Is `Span.setOperationName` similarly deprecated, and does it similarly act to override the previously given name?

**Comment by yurishkuro** [comment]
it is not deprecated, on the contrary. There are cases when the correct span name is not available at the time of span creation, for example when the span is started by a generic instrumentation in some http framework, where the best that instrumentation can do is to call the span GET or POST, but once the control gets to the real business handler it can override it with something more meaningful like "getCustomerAddress".

**Comment by robsimmons** [comment]
Makes sense! Thanks for clarifying.
