### ISSUE TITLE
Gitignore lib / dist

### ISSUE THREAD

**Issue by felixfbecker** [opentracing/opentracing-javascript#69]
I wonder why lib / dist are commited to GitHub. Usually you only publish these on NPM, just like you wouldn't commit a compiled binary to GitHub, or node_modules.

**Comment by yurishkuro** [comment]
I'm not sure either, we didn't do that for https://github.com/uber/jaeger-client-node

Perhaps the only reason is that having generated code committed allows dependency on unreleased versions via direct github path. I don't know what the common practice for that in the JS world. Given that this is after all is just an API, I don't know how strong that need is to keep lib checked in.

On the plus side, it allowed me to see diffs in the lib in your PR, so something good did come out of it :-)

**Comment by felixfbecker** [comment]
Best practice is to .gitignore the compiled JS and .npmignore the source. That way there is a clear separation of source (control) and release and you can never run into a situation where the two get out of sync (for example, because you didn't recompile after a rebase). It's true that you cannot depend from GH directly, but I would rather encourage fast releases instead.

> On the plus side, it allowed me to see diffs in the lib in your PR, so something good did come out of it :-)

Tbh I actually see that as an annoyance, because it clutters the diff with files that don't need to be reviewed 😄

**Comment by yurishkuro** [comment]
I agree with you, I think we should stop checking in lib/dist. I'm just saying that in this particular case it was useful to see transpiled code differences since we're considering replacing the transpiling mechanism. Of course, we could've provided those differences in some other way.

**Comment by bcronin** [comment]
As the person who committed the initial `.gitignore`, I don't recall any good reasons (beyond the aforementioned by @yurishkuro) and would be :+1: to having lib/dist removed.

**Comment by MarckK** [comment]
lib/dist is included in .gitignore and src/ is included in .npmignore. Can this issue now be closed?
