### ISSUE TITLE
Do we really need a Makefile?

### ISSUE THREAD

**Issue by felixfbecker** [opentracing/opentracing-javascript#73]
It seems like the basic tasks of compilation would be expressed equally well with npm scripts, which Javascript developers are way more familiar with and already have `node_modules/.bin` in their PATH. `make` is also not available on Windows.

**Comment by bcronin** [comment]
I think if the `Makefile` becomes a maintenance headache, then sure, let's get rid of it.  If it's not a burden, then it may be nice for developers who _don't_ work exclusively in JavaScript. Makefiles are not the greatest, but "most" developers have come across one at some time or another whereas `npm` can be a little mysterious for those new-ish to node. Of course, I don't have any numbers to back up that statement, so weight it appropriately :)

Either way, I don't feel too strongly about it, but have a slight preference towards keeping it if it's not a pain to do so.

...

(Somewhat off-topic, I'm _pretty sure_ that Git for Windows does install make by default. Or at least I don't recall having to do anything special beyond that to get make on my Windows system.)

**Comment by felixfbecker** [comment]
I am familiar with make but still found it confusing what I had to update to add the TS support for the normal build and webpack. It seems overkill to me.

You are probably right that make is more familiar for people who never used Node, but imo a javascript implementation should use what javascript developers know, not non-javascript developers ;) Of course the scripts should be documented in the readme.

Afaik make is only in MinGW, not in msysgit. But npm is always available.

**Comment by bcronin** [comment]
I don't feel strongly. If the Makefile is removed in the TS conversion, I won't complain :)

**Comment by yurishkuro** [comment]
+1 to remove Makefile, if possible. For people new to JS ecosystem we just need a few instructions in the Contributing file.

**Comment by tedsuo** [comment]
I'm down to replace it will a small set of scripts and instructions.

**Comment by MarckK** [comment]
Can this issue now be closed?

**Comment by yurishkuro** [comment]
+1
