### ISSUE TITLE
Import problems with 0.14

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing-javascript#79]
I was testing 0.14 with [jaeger-client-node](https://github.com/uber/jaeger-client-node), and ran into the following issue. Our client is written in ES6 and transpiled to JS with babel.

https://github.com/uber/jaeger-client-node/blob/master/test/udp_sender.js
```javascript
// L28
import opentracing from 'opentracing';
// L124
let childOfRef = new opentracing.Reference(opentracing.REFERENCE_CHILD_OF, childOfContext);
```

compiled to 
```js
var _opentracing = require('opentracing');
var _opentracing2 = _interopRequireDefault(_opentracing);
// ...
var childOfRef = new _opentracing2.default.Reference(_opentracing2.default.REFERENCE_CHILD_OF, childOfContext);
```

When running throws this error:
```
        var childOfRef = new _opentracing2.default.Reference(_opentracing2.def
                                                  ^
TypeError: Cannot read property 'Reference' of undefined
```

@felixfbecker - any idea?

**Comment by felixfbecker** [comment]
That import statement is wrong. It should be
```js
import * as opentracing from 'opentracing'
```

**Comment by yurishkuro** [comment]
ACK, that fixes it. But isn't it a serious incompatibility with 0.13?

**Comment by felixfbecker** [comment]
@yurishkuro will respond to https://github.com/opentracing/opentracing-javascript/issues/78#issuecomment-296836922 here.

TypeScript does export the default when you have a default export:
```ts
export default class IAmTheDefault {}
export class IAmNot {}
```
can be imported correctly with
```js
import IAmTheDefault from '...'
// or
import { default as IAmTheDefault, IAmNot } from '...'
```
to get an object of all exports, use `import * as ...`.
It makes absolutely no sense to default the default export to the "all exports" object and Babel 5's behavior is plain wrong here. They fixed it in the newest version, so this is definitely wrong usage that happened to work before because of a Babel bug/incorrect behaviour. Since 0.14 is a breaking version over 0.13 and the fix is easy I don't think we should add a workaround for this.

**Comment by yurishkuro** [comment]
> Since 0.14 is a breaking version over 0.13 and the fix is easy I don't think we should add a workaround for this.

My concern is more about the actual services using the API. I don't mind fixing jaeger-client itself to use the recommended syntax, but fixing the real services is extremely difficult. But the services are all in Node 0.10, not using Babel. I'll continue experimenting.

**Comment by felixfbecker** [comment]
Is it really? It's just a global search & replace (and doesn't break anything until you update the package)

**Comment by rochdev** [comment]
According to semantic versioning, a minor version bump over `0.x` is actually a major revision and can thus contain breaking changes. However, it should be properly documented. I also don't necessarily see the point of compiling such a small library anyway.

**Comment by felixfbecker** [comment]
@rochdev Did you read the changelog? https://github.com/opentracing/opentracing-javascript/blob/master/CHANGELOG.rst#0140

**Comment by yurishkuro** [comment]
> The main entry point can no longer be imported with a default import

We should elaborate on that, give the workaround.

**Comment by felixfbecker** [comment]
Yeah, sorry, I thought LightStep was the only Tracer that depended on this. It wasn't used in any examples.

I would add

> If you previously used a default import like this:
> ```js
> import opentracing from 'opentracing'
> ```
> change it to
> ```js
> import * as opentracing from 'opentracing'
> ```

**Comment by yurishkuro** [comment]
> It's just a global search & replace (and doesn't break anything until you update the package)

far from being that simple. We have 100s of services in 100s of individual Git repos with all kinds of cross-dependencies. The upgrade will happen in a low-level infra library. Fortunately, most of them do not import opentracing directly, usually indirectly, to avoid dependency hell:
```js
var opentracing = require('jaeger-client').opentracing; 
```

But some do import it directly, like this:
```js
var opentracing = require('opentracing'); 
```

Is that going to break after TypeScript? I can't verify this at the moment.

**Comment by felixfbecker** [comment]
No, that will give the expected result. It's equivalent to `import * as opentracing`

**Comment by felixfbecker** [comment]
If your services are all using ES5 then they should all continue working.

**Comment by yurishkuro** [comment]
+1, verified.
