### ISSUE TITLE
span.finish unhandled exception

### ISSUE THREAD

**Issue by frankgreco** [opentracing/opentracing-javascript#83]
This is the method signature for [`span.finish`](https://github.com/opentracing/opentracing-javascript/blob/master/src/span.ts#L168-L173)

```js
finish(finishTime?: number): void
```

This signature does not accept a callback nor is it synchronous. Hence, if there is an error reporting the span, an unhandled exception will be thrown and the node process will die. The current workaround is to watch on the `unhandledException` event as follows:

```js
process.on('uncaughtException', err => {
  console.error(err)
})
```

This seems like a very huge gap and so I'm wondering why the method signature for `span.finish` does not support callbacks. 

Additionally, is there a different way to handle errors that might be caused during the execution of `span.finish` that I am missing.

If indeed this is a bug, I can propose a solution and PR a fix. Perhaps something like:

```js
finish(finishTime?: number, callback?: function): void
```

```js
span.finish(err => console.log(err))
```

**Comment by yurishkuro** [comment]
calling `finish()` does not guarantee that the span is going to be reported, because of internal batching in the tracer. imo `finish()` must ever throw an exception - this is true of most OE methods except those that are explicitly documented to throw exceptions. So given no-exception semantics and deferred reporting, what would be the use case for having a callback?

**Comment by frankgreco** [comment]
> So given no-exception semantics

the cause of this issue is that I am getting an unhandled exception.

**Comment by yurishkuro** [comment]
That's not necessarily the API issue though. Which implementation are you using? You may want to open an issue for that project.

**Comment by frankgreco** [comment]
@yurishkuro 

here is my exception:

```
{ Error: getaddrinfo ENOTFOUND jaeger-agent.kube-system.svc.cluster.local
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'jaeger-agent.kube-system.svc.cluster.local' }
```

As you can see, I am using the [jaeger node client](https://github.com/uber/jaeger-client-node). However, Jaeger must conform to the opentracing API and as such, it has no way to bubble an error up.

**Comment by frankgreco** [comment]
Are you saying that Jaeger should gracefully "drop" the error

**Comment by yurishkuro** [comment]
That's an issue for Jaeger client, I opened a ticket there to fix it.

Do you still think the API needs a callback? If not, we can close this.

**Comment by frankgreco** [comment]
thanks! no I don't think a callback is still needed as this would go against the goals of what OT is trying to accomplish with the `span.finish` method.
