### ISSUE TITLE
Allow Access To Mock Tracer Via Opentracing Import

### ISSUE THREAD

**Issue by jhorowitz** [opentracing/opentracing-javascript#89]
Mock tracer could be incredibly useful for unit tests. I saw a TODO for moving it to its own NPM package but I think it'd be more useful if exposed here. If you think it's a good idea, I'd be happy to make a PR and take ownership of its maintenance. 

What are your thoughts?

**Comment by yurishkuro** [comment]
What do you mean by "Via Opentracing Import"? Isn't it already usable?

**Comment by jhorowitz** [comment]
I mean adding it as an export to https://github.com/opentracing/opentracing-javascript/blob/master/src/index.ts

**Comment by yurishkuro** [comment]
+1

**Comment by yurishkuro** [comment]
fixed by #98
