### ISSUE TITLE
export mocktracer in index.js

### ISSUE THREAD

**Issue by AloisReitbauer** [opentracing/opentracing-javascript#96]
Right now Mock Tracer is not exported, although it is part of the npm package. Should we remove it from the npm package or export it. Otherwise people will need to use it with a direct file system reference into node_modules which is weird.

**Comment by yurishkuro** [comment]
it should be exported

**Comment by AloisReitbauer** [comment]
Ok, then we also need to add a dependency to lodash in package.json see issue #95

**Comment by AloisReitbauer** [comment]
I am happy to create a PR if you add me to the project

**Comment by yurishkuro** [comment]
fixed by #98
